"use strict";try{(function(){var spoilers=document.getElementsByClassName('spoiler'),accessibleBtn=document.createElement('button');accessibleBtn.innerHTML='Spoiler';accessibleBtn.className='sr';accessibleBtn.setAttribute('tabindex','-1');accessibleBtn.setAttribute('aria-expanded','false');function handleSpoilerButton(event){var btn=event.target||event.srcElement,spoiler=btn.nextSibling,isExpanded=btn.getAttribute('aria-expanded')==='true';if(!isExpanded){for(var i=0;i<spoilers.length;i++){if(!spoilers[i].contains(spoiler)){spoilers[i].setAttribute('aria-hidden','true');spoilers[i].setAttribute('aria-expanded','false');spoilers[i].previousSibling.setAttribute('aria-expanded','false');}}
spoiler.setAttribute('aria-hidden','false');spoiler.setAttribute('aria-expanded','true');btn.setAttribute('aria-expanded','true');}else{spoiler.setAttribute('aria-hidden','true');spoiler.setAttribute('aria-expanded','false');btn.setAttribute('aria-expanded','false');}}
for(var i=0;i<spoilers.length;i++){if(spoilers[i].tagName.toLowerCase()!=='span')continue;var btn=accessibleBtn.cloneNode(true);if(window.addEventListener){btn.addEventListener('click',handleSpoilerButton,false);}else if(window.attachEvent){btn.attachEvent('onclick',handleSpoilerButton);}else return;btn.setAttribute('aria-controls','sp'+i);spoilers[i].parentNode.insertBefore(btn,spoilers[i]);spoilers[i].setAttribute('aria-hidden','true');spoilers[i].setAttribute('aria-expanded','false');spoilers[i].setAttribute('role','alert');spoilers[i].id='sp'+i;}})();}
catch(e){(new Image(1,1)).src='jslog?m=A11Y%20name%20'+encodeURIComponent(e.name)+'%20mess%20'+encodeURIComponent(e.message)+'%20codeName%20'+encodeURIComponent(navigator.appCodeName)+'%20appName%20'+encodeURIComponent(navigator.appName)+(e.stack?('%20stack%20'+encodeURIComponent(e.stack)):'');}
try{(function(){function getCSSNameByHref(href){return href.substring(href.lastIndexOf("/")+1,href.lastIndexOf("."));}
function getChosenStyle(){var i,a,filepath;for(i=0;(a=document.getElementsByTagName("link")[i]);i++){if(a.getAttribute("rel").indexOf("style")!==-1&&a.getAttribute("title")&&a.disabled===false){return getCSSNameByHref(a.getAttribute("href"));}}}
function setChosenStyle(name){var i,a,found=false,firstStyle=null;for(i=0;(a=document.getElementsByTagName("link")[i]);i++){if(a.getAttribute("rel").indexOf("style")!==-1&&a.getAttribute("title")){a.disabled=true;if(firstStyle===null){firstStyle=a;}
if(getCSSNameByHref(a.getAttribute("href"))===name){a.disabled=false;found=true;}}}
if(!found&&firstStyle){firstStyle.disabled=false;}}
function initialize(){var i,a,notDisabledCounter=0;for(i=0;(a=document.getElementsByTagName("link")[i]);i++){if(a.getAttribute("rel").indexOf("style")!==-1&&a.getAttribute("title")&&a.disabled===false){notDisabledCounter++;}}
if(notDisabledCounter>1){for(i=0;(a=document.getElementsByTagName("link")[i]);i++){if(a.getAttribute("rel")==='alternate stylesheet'){a.disabled=true;}}}}
function getCookie(name){if(!name)return;return decodeURIComponent(document.cookie.replace(new RegExp("(?:(?:^|.*;)\\s*"+encodeURIComponent(name).replace(/[\-\.\+\*]/g,"\\$&")+"\\s*\\=\\s*([^;]*).*$)|^.*$"),"$1"))||null;}
function setCookie(name,value){document.cookie=encodeURIComponent(name)+"="+encodeURIComponent(value)+"; expires=Tue, 19 Jan 2038 03:14:07 GMT; domain=."+location.hostname+"; path=/"+(location.protocol==='https:'?'; secure':'')+"; samesite=lax";}
var handleStyleRadio=function me(event){var btn=event.target||event.srcElement;if(btn.tagName.toLowerCase()!=='input'||btn.type!=='radio'||btn.name!=='style')return;setChosenStyle(btn.value);setCookie('style',btn.value);var successLabel=document.getElementById('style-saved'),radioLabel=btn.parentElement;if(!successLabel||!radioLabel||radioLabel.getAttribute('data-labelledby')===null)return;clearTimeout(me.timeout);successLabel.style.display='none';setTimeout(function(){successLabel.style.display='inline';},300);radioLabel.setAttribute('aria-labelledby',radioLabel.getAttribute('data-labelledby'));radioLabel.setAttribute('aria-relevant','additions');me.timeout=setTimeout(function(){successLabel.style.display='none';radioLabel.removeAttribute('aria-labelledby');},3000);}
handleStyleRadio.timeout=null;initialize();var styleCookie=getCookie('style');if(styleCookie&&styleCookie!==getChosenStyle()){setChosenStyle(styleCookie);}
var chosenOnLoad=getChosenStyle();function handleBrowserStyleSwitching(chosenOnLoad){return function(){if(chosenOnLoad!==getChosenStyle()){setCookie('style',getChosenStyle());}}}
window.onbeforeunload=handleBrowserStyleSwitching(chosenOnLoad);if(window.addEventListener){window.addEventListener('unload',handleBrowserStyleSwitching(chosenOnLoad),false);document.body.addEventListener('change',handleStyleRadio,false);}else if(window.attachEvent){window.attachEvent('onunload',handleBrowserStyleSwitching(chosenOnLoad));document.body.attachEvent('onchange',handleStyleRadio);}})();}
catch(e){(new Image(1,1)).src='jslog?m=AltCSS%20name%20'+encodeURIComponent(e.name)+'%20mess%20'+encodeURIComponent(e.message)+(e.stack?('%20stack%20'+encodeURIComponent(e.stack)):'');}